name: Override environment variables

on: push

env:

  EXAMPLE: Defined by workflow level

jobs:

  print:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${EXAMPLE}"

      - run: echo "${EXAMPLE}"
        env:
          EXAMPLE: Defined by step level

